settings:
  timer-check-seconds: 1
  save-on-quit: true
  restore-normal-location-on-free: true

server-border:
  world: "world"
  center-x: 0.0
  center-z: 0.0
  start-size-blocks: 6400.0
  weekly-increase-blocks: 1600.0
  apply-on-startup: true

exile-border:
  world: "world"
  center-x: 0.0
  center-z: 0.0
  radius-blocks: 2000000.0
  exile-spawn-min-distance: 2005000.0
  exile-spawn-max-distance: 2300000.0
  safe-teleport-tries: 100
  avoid-water: true
  avoid-lava: true
  avoid-leaves: true

return-location:
  use-config-return-if-normal-location-missing: true
  world: "world"
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

inventory:
  keep-separate-exile-inventory: true
  clear-player-on-exile: true
  restore-normal-on-free: true

punishments:
  exileremove:
    mode: "kick"
    kick-message: "&cYou have been permanently removed from the server."
    ban-reason: "Removed from server by exile punishment."

formats:
  default-time-unit: "m"
